apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: udafendo/k8demoapps:dotnetcoreappv1
        imagePullPolicy: "Always"
        envFrom:
          - configMapRef:
              name: webapp-config
        ports:
          - containerPort: 5089
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5089
      targetPort: 5089
      nodePort: 30200